version: 2

.restore-cache: &restore-cache
  - type: cache-restore
    name: Restoring dependencies
    keys:
      - project-{{checksum "boot.properties" }}-{{ checksum "build.boot" }}

.save-cache: &save-cache
  - type: cache-save
    name: Store bundle cache
    key: project-{{checksum "boot.properties" }}-{{ checksum "build.boot" }}
    paths:
      - ~/.m2
      - ~/.boot/cache/lib
      - ~/.boot/cache/bin

jobs:
  run_test:
    docker:
      - image: circleci/clojure:boot-2.8.2
    steps:
      - checkout
      - <<: *restore-cache
      - run:
          name: Boot test
          command: boot test
      - <<: *save-cache

  generate_js:
    docker:
      - image: circleci/clojure:boot-2.8.2
    steps:
      - checkout
      - <<: *restore-cache
      - run:
          name: Generate js libraries
          command: |
            mkdir -p ~/prod
            mkdir -p ~/prod-files
            boot prod -f ~/prod
            mv ~/prod/main.js ~/prod-files/main.js
            mv ~/prod/main.js.map ~/prod-files/main.js.map
            mv ~/prod/index.html ~/prod-files/index.html
      - store_artifacts:
          path: ~/prod-files

workflows:
  version: 2
  test-and-build:
    jobs:
      - run_test
      - generate_js:
          requires:
            - run_test
          filters:
            branches:
              only:
                - master
